# pg_hba_custom.conf — permite acceso al servidor principal
# Reemplaza 0.0.0.0/0 con la IP real de tu servidor Ubuntu para mayor seguridad
host    all             all             0.0.0.0/0               scram-sha-256
host    replication     all             0.0.0.0/0               scram-sha-256
